# Generated by Django 3.0.6 on 2020-05-28 15:48

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farbe', models.CharField(max_length=8)),
                ('baujahr', models.IntegerField()),
                ('kaufdatum', models.DateField()),
                ('preis', models.IntegerField()),
                ('added_by', models.ForeignKey(default=data.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was', models.TextField()),
                ('wann', models.DateField()),
                ('prio', models.CharField(choices=[('Reparatur', 'Reparatur'), ('Service', 'Service'), ('Pflege', 'Pflege'), ('Verbesserung', 'Verbesserung')], max_length=14)),
                ('km', models.IntegerField()),
                ('kostenpunkt', models.IntegerField()),
                ('added_by', models.ForeignKey(default=data.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Profile')),
                ('fahrzeug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Fahrzeug')),
            ],
        ),
        migrations.CreateModel(
            name='FahrzeugServiceProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mit_service', to='data.Fahrzeug')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fahrzeug_mit_service', to='users.Profile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Service')),
            ],
        ),
        migrations.AddField(
            model_name='fahrzeug',
            name='owners',
            field=models.ManyToManyField(related_name='fahrzeuge', through='data.FahrzeugServiceProfil', to='users.Profile'),
        ),
    ]
